version: "3.7"

services:
  my-mini:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/miniproject/index.js
      - ./phone.js:/miniproject/phone.js
      - ./email.js:/miniproject/email.js
      - ./user-cheerio.js:/miniproject/user-cheerio.js
      - ./utils.js:/miniproject/utils.js
    ports:
      - 3000:3000

  my-miniDB:
    image: mongo:5
    ports:
      - 27017:27017
