export class ProductService {
    // 판매여부 검증하는 함수
    checkSoldout = () => {
        console.log("판매가 완료됐는지 검사합니다.");
        // 2. 판매여부 검증하는 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
    };
}
