version: "3.7"

services:
    my-mini:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/miniproject/index.js
        ports:
            - 3000:3000

    my-miniDB:
        image: mongo:5
        ports:
            - 27017:27017
